### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Zbozhou** [OpenDriveLab/BeTop#3]
Thank you for your exceptional work and valuable contributions to this field. I have two questions:

1. What is the difference between BeTopNet-full and BeTopNet-e2e? I might have missed it, but I couldn't find an explanation anywhere.
2. Do you plan to release the code for nuPlan?

Looking forward to your reply.

**Comment by georgeliu233** [comment]
Hi Bozhou, thanks for your interests in our work! The "-full" version denotes the model using 64 modes and NMS for post-processing, while the "-e2e" one works directly on 6 modes. We are also working on the scrutinization for nuPlan project, due to some delay for ongoing project, you may expect the release on next month or upon.

Best

**Comment by Zbozhou** [comment]
I got it, thanks for your reply.
